PROCEDIMIENTOS_INT_PROCEDIMIENTOS_SIGCOM = {
    'PROCEDIMIENTO DE NEUMOLOGIA (apnea del sueño)':
    '15022_1-PROCEDIMIENTO DE NEUMOLOGÍA | Procedimiento',
    'PROCEDIMIENTO DE CARDIOLOGIA': '15026_1-PROCEDIMIENTOS DE CARDIOLOGÍA | Procedimiento',
    'PROCEDIMIENTOS DE HEMODINAMIA': '253_1-PROCEDIMIENTOS DE HEMODINAMIA | Procedimiento',
    'PROCEDIMIENTO ONCOLOGIA': '15038_1-PROCEDIMIENTO ONCOLOGÍA | Procedimiento',
    'PROCEDIMIENTO EBUS': '264_1-PROCEDIMIENTOS EBUS | Procedimiento',
    'PROCEDIMIENTO ECMO (1,5 horas c/u/)': '265_1-PROCEDIMIENTOS ECMO | Procedimiento',
    'PROCEDIMIENTOS ENDOSCC_x0013_PICOS(broncoscopía)':
    '267_1-PROCEDIMIENTOS ENDOSCÓPICOS | Procedimiento',
    'PROCEDIMIENTO TAVI (4 horas c/u)': '270_1-PROCEDIMIENTOS TAVI | Procedimiento',
    'ECOCARDIOGRAFIA (TT)': '537_1-ECOCARDIOGRAFÍA | Estudio',
    'ANATOMIA PATOLOGICA': '544_1-ANATOMÍA PATOLÓGICA | Estudio',
    'BANCO DE SANGRE': '51001_1-BANCO DE SANGRE | Exámen'}
